### ISSUE TITLE
sha256 doesn't follow FIPS 180-2 or FIPS 180-4 spec

### ISSUE THREAD

**Issue by danielpclark** [paulej/AESCrypt#20]
I translated the sha256.c file into Rust and read up on the FIPS 180-2 standard and I found an issue.

Rust discovered that in the second call to the `sha256_update` method within the `sha256_finish` method causes u32 to exceed its max limit.  From studying the standard and making some changes on the Rust side I found the answer.

The C code here has these following methods:

```c
#define F0(x,y,z) ((x & y) | (z & (x | y)))
#define F1(x,y,z) (z ^ (x & (y ^ z)))
```

Used here:

```c
#define P(a,b,c,d,e,f,g,h,x,K)                  \
{                                               \
    temp1 = h + S3(e) + F1(e,f,g) + K + x;      \
    temp2 = S2(a) + F0(a,b,c);                  \
    d += temp1; h = temp1 + temp2;              \
}
```

`F0` and `F1` do not follow the FIPS 180-2 standards and have a different formula.  In the specification the `F1` method would be the method `Ch` and has the following formula (in mathematical notation):

```
Ch( x, y, z) = ( x ^ y) ⊕  ( ¬x ^ z)
```

`F0` should be the `Maj` method and has this following formula (in mathematical notation):

```
Maj( x, y, z) = ( x ^ y) ⊕ ( x ^ z) ⊕ ( y ^ z)
```

In my Rust code I swapped out the methods with the following:

```rust
#[inline(always)] fn ch(x: u32, y: u32, z: u32) -> u32 { (x & y) ^ (!x & z) }
#[inline(always)] fn maj(x: u32, y: u32, z: u32) -> u32 { (x & y) ^ (x & z) ^ (y & z) }
```

This fixed the u32 addition overflow issue and is according to the FIPS 180-2 spec (which the C file comment says this adheres to) and the FIPS 180-4 spec.  Also my code now works in Rust with the tests.

I just wanted to pass along a solution I discovered and hope you find this helpful.

Cheers!

**Comment by paulej** [comment]
Given a series of AND and OR operations, it's not possible for a uint32_t to exceed its max size, since the resulting value will always be a uint32_t.

While the code I am using is quite old, I checked the latest version of this software and it still has exactly these lines of code.  This code was originally authored by Christophe Devine.  That then became part of XySSL, which then became a part of PolarisSSL, and is now called mbed and owned by Arm.  The source code can be retrieved from this page: https://tls.mbed.org/download.  (The history of this is recorded on Wikipedia: https://en.wikipedia.org/wiki/Mbed_TLS).

Nice to see this is now licensed under Apache, because that is far friendlier than GNU. :)

Anyway, perhaps the issue lies elsewhere?  Perhaps it's something specific to Rust?

Obviously since that's not my code, I cannot say definitively that there isn't a problem.  However, given that F0 still exists as defined in the version old version of the code I have, I'd say it's probably not a problem.

**Comment by danielpclark** [comment]
> Given a series of AND and OR operations, it's not possible for a uint32_t to exceed its max size, since the resulting value will always be a uint32_t.

Where that is true the results of each of these still get added and if bits are flipped in such a way that to added u32s are more than u32_max/2 then the addition will overflow.

Thanks for sharing the source origin, that's been really helpful.  I see they've rewritten a good part of the `sha256_finish` method.  I was wondering how they were adding the appropriate padding before this since I didn't see `0x80` in the code and the only test I had issue with was the multi-block test... and the finish method now has a step for the multi-block situation.

**Comment by paulej** [comment]
The sum in P() might potentially cause  values to overflow the uint32_t, but I assume that's expected. One could do a logical "and" to avoid that, but a uint32_t will do that in effect. Adding 1 to 0xFFFFFFFF will always really in a uint32_t having a value of 0.

What I do know is that there are versions of AES Crypt in C, Python, Java, JavaScript, C#, etc. and I've never encountered a case where SHA256 failed to compute the same value on different implementations.

That said, I'm tempted to update this modules only because the license is friendlier.  "One of these days", I night take that initiative.  But I'd also like to better optimize on Intel platforms where we could use native AES instructions.  Both are on my list.

**Comment by danielpclark** [comment]
> but a uint32_t will do that in effect. Adding 1 to 0xFFFFFFFF will always really in a uint32_t having a value of 0.

Thanks!  I didn't know that was C's behavior for this type.
