### ISSUE TITLE
Windows 10 installation error 

### ISSUE THREAD

**Issue by luger19** [paulej/AESCrypt#25]
When running AESCrypt.msi, Windows installs AESCrypt but when running aescrypt.exe, it will immediately close itself and when running AESCrypt32.exe, I get the error: `Usage: aescrypt32 [/d|/e] filename`. When running setup.exe, I get the error: `Fix the following problem: A newer version of Microsoft Visual C++ 2010 Redistributable was detected on the computer.`

**Comment by paulej** [comment]
This doesn't apply to the code here in GitHub, since no binaries are distributed here. You're referring to the binaries downloaded from aescrypt.com directly.

In the ZIP file, you would see a text file named "Install Notes.txt" that explains that you'll get this error trying to run setup.exe. That executable is only for older systems that don't have the libraries installed. Newer systems should only use aescrypt.msi.
