### ISSUE TITLE
missing license for the repo

### ISSUE THREAD

**Issue by chenrui333** [paulej/AESCrypt#27]
license reference list, https://spdx.org/licenses/

**Comment by paulej** [comment]
Some of the code is GNU, some not. It's complicated.

**Comment by chenrui333** [comment]
> Some of the code is GNU, some not. It's complicated.

got you, thanks for the quick reply.

**Comment by PatVax** [comment]
If I want to distribute the AESCrypt binaries in a bigger software solution via a zip file with a subdirectory for AESCrypt how should I handle licensing? I obviously would need to leave a link to AESCrypt website and possibly this repo since some code is GNU. Do I have to distribute a License file along with the binaries in their subdirectory? If so would it be the GPL?

**Comment by PatVax** [comment]
Just noticed the issue #4 Add a LICENSE file into the repository root. My guess would be to include the readme file in my AESCrypt subdirectory. Is this correct?

**Comment by paulej** [comment]
Some code is GNU. Some code is not. It's free to use, but I personally hate the GNU license. It's too restrictive.  I put a license in the source files themselves, because I cannot classify the whole project under one license or another.  I aim to remove all the GNU code.  That will resolve the confusion.

**Comment by PatVax** [comment]
I agree with you on the GNU license. But for now since I only distribute a binary I do need to leave some sort of attribution with it. Thanks I think I know what to do now.
